"""
日次成果物を 4 系統（Drive / R2 / Dropbox / GitHub Release）にミラーアップロードする CLI。
同一 run-date + 同一ファイルセットで再実行しても上書きで冪等。
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from datetime import datetime
from pathlib import Path

_repo_root = Path(__file__).resolve().parent.parent
if str(_repo_root) not in sys.path:
    sys.path.insert(0, str(_repo_root))

from scripts.storage.paths import build_day_path


def _parse_run_date(s: str) -> tuple[str, str]:
    """YYYY-MM-DD -> (YYYY-MM, YYYY-MM-DD)。"""
    if len(s) != 10 or s[4] != "-" or s[7] != "-":
        raise ValueError(f"run-date は YYYY-MM-DD 形式で指定してください: {s}")
    return s[:7], s


def _mime_for(path: Path) -> str:
    suf = path.suffix.lower()
    if suf == ".csv":
        return "text/csv"
    if suf in (".xlsx", ".xls"):
        return "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    return "application/octet-stream"


def run(
    run_date: str,
    files: list[Path],
    targets: set[str],
) -> int:
    """
    指定ファイルを有効なターゲットにアップロードする。
    戻り値: 0 は全成功、非 0 は 1 つ以上失敗。
    """
    month, day = _parse_run_date(run_date)
    run_d = datetime.strptime(run_date, "%Y-%m-%d").date()
    day_path = build_day_path(run_d, "work")

    results: dict[str, str] = {}
    any_failed = False

    if "drive" in targets:
        try:
            from scripts.gdrive.upload_to_work import run as drive_run

            file_ids = [str(f) for f in files]
            last_id = drive_run(month, file_ids, day=run_date)
            if last_id:
                results["drive_file_id"] = last_id
        except Exception as e:
            print(f"[Drive] エラー: {e}", file=sys.stderr)
            any_failed = True

    if "r2" in targets:
        try:
            from scripts.storage.r2_client import R2StorageAdapter

            adapter = R2StorageAdapter()
            for f in files:
                content = f.read_bytes()
                key = adapter.upload_file(day_path, f.name, content, _mime_for(f))
                results["r2_key"] = key
        except Exception as e:
            print(f"[R2] エラー: {e}", file=sys.stderr)
            any_failed = True

    if "dropbox" in targets:
        try:
            from scripts.storage.dropbox_client import DropboxStorageAdapter

            adapter = DropboxStorageAdapter()
            for f in files:
                content = f.read_bytes()
                full_path = adapter.upload_file(day_path, f.name, content, _mime_for(f))
                results["dropbox_path"] = full_path
        except Exception as e:
            print(f"[Dropbox] エラー: {e}", file=sys.stderr)
            any_failed = True

    if "github" in targets:
        tag = f"daily-{run_date[:7].replace('-', '')}"
        try:
            view = subprocess.run(
                ["gh", "release", "view", tag],
                capture_output=True,
                text=True,
                cwd=_repo_root,
            )
            if view.returncode != 0:
                create = subprocess.run(
                    ["gh", "release", "create", tag, "-t", f"Daily {run_date[:7]}", "-n", "Autogenerated"],
                    capture_output=True,
                    text=True,
                    cwd=_repo_root,
                )
                if create.returncode != 0 and "already exists" not in (create.stderr or "").lower():
                    print(f"[GitHub] release create エラー: {create.stderr}", file=sys.stderr)
                    any_failed = True
            if not any_failed:
                for f in files:
                    subprocess.run(
                        ["gh", "release", "upload", tag, str(f), "--clobber"],
                        check=True,
                        capture_output=True,
                        cwd=_repo_root,
                    )
                results["gh_release_tag"] = tag
        except (FileNotFoundError, subprocess.CalledProcessError) as e:
            print(f"[GitHub] エラー: {e}", file=sys.stderr)
            any_failed = True

    for k, v in results.items():
        print(f"{k}={v}")

    return 1 if any_failed else 0


def main() -> None:
    parser = argparse.ArgumentParser(
        description="日次成果物を Drive / R2 / Dropbox / GitHub Release にミラーアップロードする。",
    )
    parser.add_argument(
        "--run-date",
        required=True,
        metavar="YYYY-MM-DD",
        help="対象日",
    )
    parser.add_argument(
        "--files",
        nargs="+",
        required=True,
        metavar="FILE",
        help="アップロードするファイルパス",
    )
    parser.add_argument(
        "--targets",
        default="drive,r2,dropbox,github",
        help="有効にするターゲット（カンマ区切り）。省略時は全有効。",
    )
    args = parser.parse_args()

    targets = {t.strip().lower() for t in args.targets.split(",") if t.strip()}
    valid = {"drive", "r2", "dropbox", "github"}
    invalid = targets - valid
    if invalid:
        print(f"エラー: 不明なターゲット: {invalid}。有効: {valid}", file=sys.stderr)
        sys.exit(1)

    files = [Path(p) for p in args.files]
    for f in files:
        if not f.is_file():
            print(f"エラー: ファイルが見つかりません: {f}", file=sys.stderr)
            sys.exit(1)

    try:
        _parse_run_date(args.run_date)
    except ValueError as e:
        print(f"エラー: {e}", file=sys.stderr)
        sys.exit(1)

    code = run(args.run_date, files, targets)
    sys.exit(code)


if __name__ == "__main__":
    try:
        main()
    except SystemExit:
        raise
    except Exception as e:
        print(f"エラー: {type(e).__name__}: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc(file=sys.stderr)
        sys.exit(1)
