"""
日次成果物を 4 系統（Drive / R2 / Dropbox / GitHub Release）にミラーアップロードする CLI。
同一 run-date + 同一ファイルセットで再実行しても上書きで冪等。
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from datetime import datetime
from pathlib import Path

_repo_root = Path(__file__).resolve().parent.parent
if str(_repo_root) not in sys.path:
    sys.path.insert(0, str(_repo_root))

from scripts.storage.paths import build_day_path, build_month_path

# 要求した全ターゲットが失敗したときの終了コード（1 は CLI 引数エラー用のため避ける）
EXIT_UPLOAD_ALL_TARGETS_FAILED = 2


def _parse_run_date(s: str) -> tuple[str, str]:
    """YYYY-MM-DD -> (YYYY-MM, YYYY-MM-DD)。"""
    if len(s) != 10 or s[4] != "-" or s[7] != "-":
        raise ValueError(f"run-date は YYYY-MM-DD 形式で指定してください: {s}")
    return s[:7], s


def _mime_for(path: Path) -> str:
    suf = path.suffix.lower()
    if suf == ".csv":
        return "text/csv"
    if suf in (".xlsx", ".xls"):
        return "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    return "application/octet-stream"


def run(
    run_date: str,
    files: list[Path],
    targets: set[str],
) -> int:
    """
    指定ファイルを有効なターゲットにアップロードする。

    終了コード:
        0 — 少なくとも 1 系統は成功（全成功または一部失敗の degraded）。
        EXIT_UPLOAD_ALL_TARGETS_FAILED — targets が空でなく、要求した全ターゲットが失敗。

    stdout の末尾に常に次の 2 行を出力する:
        upload_status=ok|degraded|failed
        upload_failed_targets=- または失敗したターゲット名をカンマ区切り（ソート済み）
    """
    _month, _day = _parse_run_date(run_date)
    run_d = datetime.strptime(run_date, "%Y-%m-%d").date()
    # ルーティング:
    # - CSV: work の日フォルダ（0011_work/YYYY-MM/YYYY-MM-DD/）
    # - XLSX: paid の月フォルダ（0012_paid/YYYY-MM/）
    work_day_path = build_day_path(run_d, "work")
    paid_month_path = build_month_path(run_d, "paid")

    results: dict[str, str] = {}
    failed_targets: set[str] = set()

    def _dest_path_for(f: Path) -> str:
        suf = f.suffix.lower()
        if suf in (".xlsx", ".xls"):
            return paid_month_path
        return work_day_path

    if "drive" in targets:
        try:
            from scripts.gdrive.drive_client import (
                GoogleDriveAdapter,
                build_service,
                get_credentials,
                get_folder_id_paid,
                get_folder_id_work,
            )

            service = build_service(get_credentials())
            adapter = GoogleDriveAdapter(service)

            for f in files:
                content = f.read_bytes()
                dest_path = _dest_path_for(f).strip("/")
                parts = [p for p in dest_path.split("/") if p]
                if not parts:
                    raise ValueError(f"Drive宛先パスが不正です: {dest_path}")
                root = parts[0]
                if root == "0011_work":
                    parent_id = get_folder_id_work()
                elif root == "0012_paid":
                    parent_id = get_folder_id_paid()
                else:
                    raise ValueError(f"Drive宛先プレフィックスが不正です: {root}")

                for folder_name in parts[1:]:
                    parent_id = adapter.get_or_create_folder(parent_id, folder_name)

                file_id, _ = adapter.upload_file(
                    parent_id, f.name, content, mime_type=_mime_for(f)
                )
                results["drive_file_id"] = file_id
        except Exception as e:
            print(f"[Drive] エラー: {e}", file=sys.stderr)
            # Drive は凍結や認証エラーがあっても他 3 系統が動けばよい前提のため、
            # エラーはログに残すのみで致命扱いにはしない。
            failed_targets.add("drive")

    if "r2" in targets:
        try:
            from scripts.storage.r2_client import R2StorageAdapter

            adapter = R2StorageAdapter()
            for f in files:
                content = f.read_bytes()
                key = adapter.upload_file(_dest_path_for(f), f.name, content, _mime_for(f))
                results["r2_key"] = key
        except Exception as e:
            print(f"[R2] エラー: {e}", file=sys.stderr)
            failed_targets.add("r2")

    if "dropbox" in targets:
        try:
            from scripts.storage.dropbox_client import DropboxStorageAdapter

            adapter = DropboxStorageAdapter()
            for f in files:
                content = f.read_bytes()
                full_path = adapter.upload_file(_dest_path_for(f), f.name, content, _mime_for(f))
                results["dropbox_path"] = full_path
        except Exception as e:
            print(f"[Dropbox] エラー: {e}", file=sys.stderr)
            failed_targets.add("dropbox")

    if "github" in targets:
        tag = f"daily-{run_date[:7].replace('-', '')}"
        try:
            view = subprocess.run(
                ["gh", "release", "view", tag],
                capture_output=True,
                text=True,
                cwd=_repo_root,
            )
            if view.returncode != 0:
                create = subprocess.run(
                    ["gh", "release", "create", tag, "-t", f"Daily {run_date[:7]}", "-n", "Autogenerated"],
                    capture_output=True,
                    text=True,
                    cwd=_repo_root,
                )
                if create.returncode != 0 and "already exists" not in (create.stderr or "").lower():
                    print(f"[GitHub] release create エラー: {create.stderr}", file=sys.stderr)
                    # GitHub Release は管理用バックアップ枠のため、権限不足等で失敗しても致命扱いにはしない。
                    failed_targets.add("github")
            # Release が存在する前提で、アップロードを試みる（失敗しても他ターゲットには影響させない）。
            for f in files:
                try:
                    subprocess.run(
                        ["gh", "release", "upload", tag, str(f), "--clobber"],
                        check=True,
                        capture_output=True,
                        cwd=_repo_root,
                    )
                    results["gh_release_tag"] = tag
                except subprocess.CalledProcessError as e:
                    stderr_text = ""
                    if isinstance(e.stderr, bytes):
                        stderr_text = e.stderr.decode("utf-8", errors="ignore")
                    elif isinstance(e.stderr, str):
                        stderr_text = e.stderr
                    if stderr_text.strip():
                        print(f"[GitHub] upload エラー: {stderr_text.strip()}", file=sys.stderr)
                    else:
                        print(f"[GitHub] upload エラー: {e}", file=sys.stderr)
                    failed_targets.add("github")
                    break
        except (FileNotFoundError, subprocess.CalledProcessError) as e:
            print(f"[GitHub] エラー: {e}", file=sys.stderr)
            # GitHub Release 失敗も致命扱いにはしない（ログのみ）
            failed_targets.add("github")

    for k, v in results.items():
        print(f"{k}={v}")

    if failed_targets:
        print(f"upload_warnings={','.join(sorted(failed_targets))}", file=sys.stderr)

    if not targets:
        upload_status = "ok"
        failed_csv = "-"
        exit_code = 0
    elif failed_targets == targets:
        upload_status = "failed"
        failed_csv = ",".join(sorted(failed_targets))
        exit_code = EXIT_UPLOAD_ALL_TARGETS_FAILED
    elif failed_targets:
        upload_status = "degraded"
        failed_csv = ",".join(sorted(failed_targets))
        exit_code = 0
    else:
        upload_status = "ok"
        failed_csv = "-"
        exit_code = 0

    print(f"upload_status={upload_status}")
    print(f"upload_failed_targets={failed_csv}")
    return exit_code


def main() -> None:
    parser = argparse.ArgumentParser(
        description="日次成果物を Drive / R2 / Dropbox / GitHub Release にミラーアップロードする。",
    )
    parser.add_argument(
        "--run-date",
        required=True,
        metavar="YYYY-MM-DD",
        help="対象日",
    )
    parser.add_argument(
        "--files",
        nargs="+",
        required=True,
        metavar="FILE",
        help="アップロードするファイルパス",
    )
    parser.add_argument(
        "--targets",
        default="drive,r2,dropbox,github",
        help="有効にするターゲット（カンマ区切り）。省略時は全有効。",
    )
    args = parser.parse_args()

    targets = {t.strip().lower() for t in args.targets.split(",") if t.strip()}
    valid = {"drive", "r2", "dropbox", "github"}
    invalid = targets - valid
    if invalid:
        print(f"エラー: 不明なターゲット: {invalid}。有効: {valid}", file=sys.stderr)
        sys.exit(1)

    if not targets:
        print("エラー: --targets が空です。少なくとも 1 つ指定してください。", file=sys.stderr)
        sys.exit(1)

    files = [Path(p) for p in args.files]
    for f in files:
        if not f.is_file():
            print(f"エラー: ファイルが見つかりません: {f}", file=sys.stderr)
            sys.exit(1)

    try:
        _parse_run_date(args.run_date)
    except ValueError as e:
        print(f"エラー: {e}", file=sys.stderr)
        sys.exit(1)

    code = run(args.run_date, files, targets)
    sys.exit(code)


if __name__ == "__main__":
    try:
        main()
    except SystemExit:
        raise
    except Exception as e:
        print(f"エラー: {type(e).__name__}: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc(file=sys.stderr)
        sys.exit(1)
